### ISSUE TITLE
How to deal with "latest" files.

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-users/mrxv#6]
At the moment, we copy the latest geometry and mask for any given detector. 
@valmar I believe you had something else in mind, should we discuss this here?

**Comment by valmar** [comment]
So, in general, to better help the users, I think we should have a clear idea of which version of the geometry/mask combination they are using. If we use symlinks or names like "_latest", we cannot know. I suggest that we either use arbitrary names like "geometry_sabine.geom", or even better, dated files, like "geometry-2022-05-09v1.geom"

**Comment by valmar** [comment]
From the technical point of view, the "lastest" files should, in my opinion, not contain the latest geom or map at all, but just the name of the file containing the latest geom and map.

The script should: download the latest file, open it, read the name, and download the file pointed by the name
I volunteer to write this part of the deployment script, of course!
